# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ede288033938c5375dba21da0ead91add743462693dd9aac9f06a0af38362bebbb30f7035d4654ed97f69781848f47e2e48961b99f02053eb3a299bfacc4c370

test:
  secret_key_base: 7f79c9426b550b0d7f170cdb5b39b783b8bd057ba08073efa01d05338b3615704a94db0378e269c00b07138d1a5ffc953be7f9b2b6c5a9a88b3e9e0e7cfcd4a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
